import React from 'react';
import styles from './terms.module.css';

export const metadata = {
    title: 'Terms of Service | Tally',
    description: 'Terms of Service for Tally - Personal Finance Manager',
};

const sections = [
    {
        id: 'eligibility',
        title: '1. Eligibility and Account Registration',
        content: [
            {
                type: 'paragraph',
                text: 'You must be at least 18 years old to use the Service. By creating an account, you represent that the information you provide is accurate and that you are legally capable of entering into these Terms. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.'
            }
        ]
    },
    {
        id: 'nature',
        title: '2. Nature of the Service (No Financial Advice)',
        content: [
            {
                type: 'paragraph',
                text: 'Tally is a personal finance tracking and analytics tool intended for informational and organizational purposes only. The Service does not provide financial, legal, tax, or investment advice. Any insights, calculations, or summaries generated by the Service are provided for convenience only and should not be relied upon as a substitute for professional advice. You acknowledge that any financial decisions you make are solely your responsibility.'
            }
        ]
    },
    {
        id: 'user-content',
        title: '3. User Content and Responsibility',
        content: [
            {
                type: 'paragraph',
                text: 'You are solely responsible for the accuracy and completeness of any data you input into the Service, including financial transactions, bills, and goals. Tally does not verify user-submitted information and makes no representations regarding the accuracy of outputs generated from such data.'
            },
            {
                type: 'paragraph',
                text: 'You retain ownership of your content. By using the Service, you grant Tally a limited license to store and process your content solely for the purpose of providing the Service.'
            }
        ]
    },
    {
        id: 'acceptable-use',
        title: '4. Acceptable Use',
        content: [
            {
                type: 'paragraph',
                text: 'You agree not to misuse the Service. Prohibited activities include, but are not limited to:'
            },
            {
                type: 'list',
                items: [
                    'Attempting to gain unauthorized access to the Service or its systems',
                    'Interfering with or disrupting system security or integrity',
                    'Introducing malicious code, viruses, or harmful software',
                    'Scraping, crawling, or harvesting data from the Service',
                    'Reverse engineering or attempting to extract the source code',
                    'Using the Service for any unlawful or fraudulent purpose',
                    'Impersonating another person or entity'
                ]
            },
            {
                type: 'paragraph',
                text: 'We reserve the right to suspend or terminate accounts that violate these Terms or pose a risk to the security or integrity of the Service.'
            }
        ]
    },
    {
        id: 'availability',
        title: '5. Service Availability and Modifications',
        content: [
            {
                type: 'paragraph',
                text: 'The Service is provided on an "as is" and "as available" basis. We do not guarantee uninterrupted availability, uptime, or error-free operation. We may modify, suspend, or discontinue any part of the Service at any time without prior notice.'
            },
            {
                type: 'paragraph',
                text: 'We are not liable for any loss resulting from downtime, data loss, feature changes, or service interruptions. We recommend that you maintain independent records of your financial data.'
            }
        ]
    },
    {
        id: 'termination',
        title: '6. Account Termination',
        content: [
            {
                type: 'paragraph',
                text: 'You may delete your account at any time through the Service settings. We reserve the right to suspend or terminate your account if you violate these Terms or if continued use of the Service may pose legal or security risks.'
            },
            {
                type: 'paragraph',
                text: 'Upon termination, your access to the Service will end immediately, and your data may be deleted in accordance with our Privacy Policy and data retention policies.'
            }
        ]
    },
    {
        id: 'liability',
        title: '7. Limitation of Liability',
        content: [
            {
                type: 'paragraph',
                text: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, TALLY AND ITS OPERATOR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, FINANCIAL LOSSES, OR DATA LOSS, ARISING OUT OF OR RELATED TO YOUR USE OF (OR INABILITY TO USE) THE SERVICE.'
            },
            {
                type: 'paragraph',
                text: 'In no event shall our total liability to you for all claims exceed the amount you paid to use the Service, if any, during the twelve (12) months preceding the claim, or one hundred dollars ($100), whichever is greater.'
            }
        ]
    },
    {
        id: 'warranties',
        title: '8. Disclaimer of Warranties',
        content: [
            {
                type: 'paragraph',
                text: 'THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL MEET YOUR REQUIREMENTS, BE ERROR-FREE, OR PRODUCE ACCURATE FINANCIAL INSIGHTS.'
            },
            {
                type: 'paragraph',
                text: 'No advice or information, whether oral or written, obtained from Tally or through the Service shall create any warranty not expressly stated herein.'
            }
        ]
    },
    {
        id: 'indemnification',
        title: '9. Indemnification',
        content: [
            {
                type: 'paragraph',
                text: 'You agree to indemnify, defend, and hold harmless Tally and its operator from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys\' fees) arising out of or related to:'
            },
            {
                type: 'list',
                items: [
                    'Your access to or use of the Service',
                    'Your violation of these Terms',
                    'Your violation of any rights of a third party',
                    'Your misuse of any data, features, or outputs of the Service'
                ]
            }
        ]
    },
    {
        id: 'third-party',
        title: '10. Third-Party Services',
        content: [
            {
                type: 'paragraph',
                text: 'The Service may integrate with third-party services for authentication (Google, GitHub) and other functionality. We are not responsible for the availability, security, accuracy, or practices of any third-party services.'
            },
            {
                type: 'paragraph',
                text: 'Your use of such third-party services is governed by their respective terms and privacy policies. We encourage you to review those policies before connecting your accounts.'
            }
        ]
    },
    {
        id: 'governing-law',
        title: '11. Governing Law and Venue',
        content: [
            {
                type: 'paragraph',
                text: 'These Terms shall be governed by and construed in accordance with the laws of the Commonwealth of Kentucky, United States, without regard to its conflict of law principles.'
            },
            {
                type: 'paragraph',
                text: 'Any legal action or proceeding arising out of or relating to these Terms or the Service shall be brought exclusively in the state or federal courts located in Kentucky. You consent to the personal jurisdiction of such courts.'
            }
        ]
    },
    {
        id: 'changes',
        title: '12. Changes to These Terms',
        content: [
            {
                type: 'paragraph',
                text: 'We reserve the right to update or modify these Terms at any time. Changes will be effective upon posting to the Service. We will indicate the "Last Updated" date at the top of this page. Your continued use of the Service after any changes constitutes acceptance of the revised Terms.'
            },
            {
                type: 'paragraph',
                text: 'If we make material changes that significantly affect your rights, we will make reasonable efforts to notify you via email or a prominent notice within the Service.'
            }
        ]
    },
    {
        id: 'contact',
        title: '13. Contact Us',
        content: [
            {
                type: 'paragraph',
                text: 'If you have questions about these Terms or need to report a violation, please contact us at:'
            },
            {
                type: 'contact',
                lines: [
                    'Tally — Personal Finance Manager',
                    'Developer: Daniel Pinzon',
                    'Email: danielfpinzonr@gmail.com'
                ]
            }
        ]
    }
];

export default function TermsPage() {
    const effectiveDate = 'February 24, 2026';

    return (
        <div className={styles.pageWrapper}>
            <div className={styles.container}>
                {/* Header */}
                <div className={styles.header}>
                    <div className={styles.badge}>Legal</div>
                    <h1 className={styles.title}>Terms of Service</h1>
                    <p className={styles.subtitle}>
                        Please read these terms carefully before using Tally. They govern your access to and use of our Service.
                    </p>
                    <div className={styles.meta}>
                        <span className={styles.metaItem}>
                            <span className={styles.metaLabel}>Effective Date:</span> {effectiveDate}
                        </span>
                        <span className={styles.metaDivider}>·</span>
                        <span className={styles.metaItem}>
                            <span className={styles.metaLabel}>Version:</span> 1.0
                        </span>
                    </div>
                </div>

                <div className={styles.layout}>
                    {/* Table of Contents */}
                    <aside className={styles.toc}>
                        <div className={styles.tocCard}>
                            <h2 className={styles.tocTitle}>Contents</h2>
                            <nav>
                                <ol className={styles.tocList}>
                                    {sections.map((section) => (
                                        <li key={section.id}>
                                            <a href={`#${section.id}`} className={styles.tocLink}>
                                                {section.title}
                                            </a>
                                        </li>
                                    ))}
                                </ol>
                            </nav>
                        </div>
                    </aside>

                    {/* Main Content */}
                    <main className={styles.content}>
                        {sections.map((section) => (
                            <section key={section.id} id={section.id} className={styles.section}>
                                <h2 className={styles.sectionTitle}>{section.title}</h2>
                                {renderContent(section.content)}
                            </section>
                        ))}

                        <div className={styles.footer}>
                            <p>These Terms were last updated on <strong>{effectiveDate}</strong>. Continued use of the Service after any changes constitutes your acceptance of the revised Terms.</p>
                        </div>
                    </main>
                </div>
            </div>
        </div>
    );
}

function renderContent(content) {
    return content.map((block, i) => {
        if (block.type === 'paragraph') {
            return <p key={i} className={styles.paragraph}>{block.text}</p>;
        }
        if (block.type === 'list') {
            return (
                <ul key={i} className={styles.list}>
                    {block.items.map((item, j) => (
                        <li key={j} className={styles.listItem}>{item}</li>
                    ))}
                </ul>
            );
        }
        if (block.type === 'contact') {
            return (
                <div key={i} className={styles.contactBlock}>
                    {block.lines.map((line, j) => (
                        <p key={j} className={styles.contactLine}>{line}</p>
                    ))}
                </div>
            );
        }
        return null;
    });
}
