#Stage 1: Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /backendTally

#restore
COPY ["backendTally/backendTally.csproj", "backendTally/"]
RUN dotnet restore 'backendTally/backendTally.csproj'

#build
COPY ["backendTally", "backendTally/"]
WORKDIR /backendTally
RUN dotnet build 'backendTally.csproj' - c Release -o /app/build



# Stage 2: Publish stage
FROM build as publish
RUN dotnet publish 'backendTally.csproj' - c Release -o /app/publish

# Stage 3: Run Stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0
EXPOSE 5
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "backendTally.dll" ]
